site_name: My Docs
nav:
  - Home: index.md
  - Quantum Angular Momentum: quantum_angular_momentum.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
